services:
  - type: web
    name: mi-player-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
